server:
  port: 8601
spring:
  data:
    mongodb:
      database: clients-management
      port: 27017
      host: http://localhost
  application:
    name: client-management-service
secret: This is my secret
